baseURL: https://christopherdavisuci.github.io/quickstart/
languageCode: en-us
title: My second Hugo Site theme
theme: "PaperMod"

params:
    profileMode:
        enabled: true
        title: "Christopher Davis" # optional default will be site title
        subtitle: "This is subtitle"
        imageUrl: "/img/dv.png" # optional
        imageTitle: "Me near Death Valley" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Github
              url: "https://github.com/ChristopherDavisUCI"